In [3]:
import numpy as np
import pandas as pd
import tokenize

In [4]:
df = pd.read_csv('news_articles.csv')
df

author                      published  \
0        Barracuda Brigade  2016-10-26T21:41:00.000+03:00   
1     reasoning with facts  2016-10-29T08:47:11.259+03:00   
2        Barracuda Brigade  2016-10-31T01:41:49.479+02:00   
3                   Fed Up  2016-11-01T05:22:00.000+02:00   
4                   Fed Up  2016-11-01T21:56:00.000+02:00   
...                    ...                            ...   
2091           -NO AUTHOR-  2016-10-27T15:36:10.573+03:00   
2092           -NO AUTHOR-  2016-10-27T15:36:10.671+03:00   
2093           -NO AUTHOR-  2016-10-27T13:30:00.000+03:00   
2094           -NO AUTHOR-  2016-10-27T15:58:41.935+03:00   
2095           Eddy Lavine  2016-10-28T01:02:00.000+03:00   

                                                  title  \
0     muslims busted they stole millions in govt ben...   
1     re why did attorney general loretta lynch plea...   
2     breaking weiner cooperating with fbi on hillar...   
3     pin drop speech by father of daughter kidnappe...   
4     fantastic trumps  point plan to reform healthc...   
...                                                 ...   
2091          teens walk free after gangrape conviction   
2092         school named for munichmassacre mastermind   
2093                      russia unveils satan  missile   
2094              check out hillarythemed haunted house   
2095  cannabis aficionados develop thca crystalline ...   

                                                   text language  \
0     print they should pay all the back all the mon...  english   
1     why did attorney general loretta lynch plead t...  english   
2     red state  \nfox news sunday reported this mor...  english   
3     email kayla mueller was a prisoner and torture...  english   
4     email healthcare reform to make america great ...  english   
...                                                 ...      ...   
2091                                                NaN  english   
2092                                                NaN  english   
2093                                                NaN  english   
2094                                                NaN  english   
2095                                                NaN      NaN   

                 site_url                                       main_img_url  \
0     100percentfedup.com  http://bb4sp.com/wp-content/uploads/2016/10/Fu...   
1     100percentfedup.com  http://bb4sp.com/wp-content/uploads/2016/10/Fu...   
2     100percentfedup.com  http://bb4sp.com/wp-content/uploads/2016/10/Fu...   
3     100percentfedup.com  http://100percentfedup.com/wp-content/uploads/...   
4     100percentfedup.com  http://100percentfedup.com/wp-content/uploads/...   
...                   ...                                                ...   
2091              wnd.com  http://www.wnd.com/files/2016/10/hillary_haunt...   
2092              wnd.com  http://www.wnd.com/files/2016/10/rambo_richard...   
2093              wnd.com  http://www.wnd.com/files/2016/10/skype_sex_sca...   
2094              wnd.com  http://worldtruth.tv/wp-content/uploads/2016/1...   
2095                  NaN                                                NaN   

      type label                            title_without_stopwords  \
0     bias  Real        muslims busted stole millions govt benefits   
1     bias  Real         attorney general loretta lynch plead fifth   
2     bias  Real  breaking weiner cooperating fbi hillary email ...   
3     bias  Real  pin drop speech father daughter kidnapped kill...   
4     bias  Real  fantastic trumps point plan reform healthcare ...   
...    ...   ...                                                ...   
2091  bias  Real  good samaritan wearing indian headdress disarm...   
2092  bias  Real                 skype sex scam fortune built shame   
2093    bs  Fake  cannabis aficionados develop thca crystalline ...   
2094    bs  Fake                                              title   
2095   NaN   NaN   

In [5]:
df.shape

(2096, 12)

In [6]:
df['text'][0]

'print they should pay all the back all the money plus interest the entire family and everyone who came in with them need to be deported asap why did it take two years to bust them \nhere we go again another group stealing from the government and taxpayers a group of somalis stole over four million in government benefits over just  months \nweve reported on numerous cases like this one where the muslim refugeesimmigrants commit fraud by scamming our systemits way out of control more related'

In [7]:
df = df[['text','label']]
df

text label
0     print they should pay all the back all the mon...  Real
1     why did attorney general loretta lynch plead t...  Real
2     red state  \nfox news sunday reported this mor...  Real
3     email kayla mueller was a prisoner and torture...  Real
4     email healthcare reform to make america great ...  Real
...                                                 ...   ...
2091                                                NaN  Real
2092                                                NaN  Real
2093                                                NaN  Fake
2094                                                NaN  Fake
2095                                                NaN   NaN

[2096 rows x 2 columns]

In [8]:
df = df.dropna()
df

text label
0     print they should pay all the back all the mon...  Real
1     why did attorney general loretta lynch plead t...  Real
2     red state  \nfox news sunday reported this mor...  Real
3     email kayla mueller was a prisoner and torture...  Real
4     email healthcare reform to make america great ...  Real
...                                                 ...   ...
2045  check out hillarythemed haunted house anticlin...  Real
2046  good samaritan wearing indian headdress disarm...  Real
2047  skype sex scam  a fortune built on shame moroc...  Real
2048  posted by eddie while the skyhigh potency may ...  Real
2049  billion even after they are known to be keepin...  Real

[2050 rows x 2 columns]

In [9]:
df.shape

(2050, 2)

In [10]:
df.label.value_counts()

Fake    1292
Real     758
Name: label, dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2050 entries, 0 to 2049
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   text    2050 non-null   object
 1   label   2050 non-null   object
dtypes: object(2)
memory usage: 48.0+ KB


In [12]:
df['label num'] = df['label'].map({'Fake':0,'Real':1})
df.sample(5)

C:\Users\ANURAG KUMAR\AppData\Local\Temp\ipykernel_25240\2319948180.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['label num'] = df['label'].map({'Fake':0,'Real':1})


text label  label num
403   hispanic crowd boos marco rubio off stage rafa...  Fake          0
1122  whos really to blame for the corrupting influe...  Real          1
355   professor dr mujahid kamran vicechancellor of ...  Fake          0
1461  us admits afghan strike likely caused civilian...  Real          1
1848  this proves that even though the power elites ...  Fake          0

In [13]:
!python -m spacy download en_core_web_lg

Defaulting to user installation because normal site-packages is not writeable
                                              0.0/587.7 MB ? eta -:--:--
                                            0.0/587.7 MB 640.0 kB/s eta 0:15:19
                                            0.1/587.7 MB 648.1 kB/s eta 0:15:07
                                            0.1/587.7 MB 871.5 kB/s eta 0:11:15
                                              0.2/587.7 MB 1.1 MB/s eta 0:08:40
                                              0.3/587.7 MB 1.1 MB/s eta 0:08:39
                                              0.5/587.7 MB 1.8 MB/s eta 0:05:25
                                              0.6/587.7 MB 1.8 MB/s eta 0:05:27
                                              1.0/587.7 MB 2.6 MB/s eta 0:03:42
                                              1.2/587.7 MB 2.9 MB/s eta 0:03:20
                                              1.4/587.7 MB 3.1 MB/s eta 0:03:12
                                              1.5

In [14]:
import spacy
nlp = spacy.load("en_core_web_lg")

In [15]:
df.head()

text label  label num
0  print they should pay all the back all the mon...  Real          1
1  why did attorney general loretta lynch plead t...  Real          1
2  red state  \nfox news sunday reported this mor...  Real          1
3  email kayla mueller was a prisoner and torture...  Real          1
4  email healthcare reform to make america great ...  Real          1

In [16]:
df['vector'] = df['text'].apply(lambda x:nlp(x).vector)
df.head()

C:\Users\ANURAG KUMAR\AppData\Local\Temp\ipykernel_25240\1388213903.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['vector'] = df['text'].apply(lambda x:nlp(x).vector)


text label  label num  \
0  print they should pay all the back all the mon...  Real          1   
1  why did attorney general loretta lynch plead t...  Real          1   
2  red state  \nfox news sunday reported this mor...  Real          1   
3  email kayla mueller was a prisoner and torture...  Real          1   
4  email healthcare reform to make america great ...  Real          1   

                                              vector  
0  [-2.039584, 0.94853497, -3.2389774, 0.69341654...  
1  [-1.5572332, 1.2933079, -2.2639158, 0.28888497...  
2  [-1.509511, 1.1297165, -2.2754374, 0.3095904, ...  
3  [-2.0995321, 1.7238559, -2.7781312, -0.1512340...  
4  [-1.6003742, 1.6297426, -3.3002098, 0.3715292,...

In [17]:
from sklearn.model_selection import train_test_split


In [18]:
x_train,x_test,y_train,y_test = train_test_split(df.vector.values,df['label num'])

In [19]:
x_train.shape

(1537,)

In [20]:
x_test.shape

(513,)

In [21]:
y_train.shape

(1537,)

In [63]:
y_test.shape

(410,)

In [22]:
x_train_2d = np.stack(x_train)
x_test_2d = np.stack(x_test)
x_train_2d

array([[-1.1334655 ,  1.2461326 , -1.9667085 , ..., -0.5025186 ,
        -3.2085075 ,  0.35673523],
       [-1.2023267 ,  1.8388191 , -2.509849  , ..., -0.36182547,
        -3.1195042 ,  1.7047609 ],
       [-2.7482483 , -0.17344947, -2.7220817 , ..., -2.5256948 ,
        -2.645433  ,  0.71128637],
       ...,
       [-2.1639113 ,  1.3592902 , -2.3997428 , ..., -1.2120215 ,
        -2.8267977 ,  0.73079085],
       [ 0.7589233 ,  3.8653698 , -2.7489114 , ...,  2.0406976 ,
        -5.3698287 ,  2.7564008 ],
       [-1.8477422 ,  1.6536821 , -3.0938554 , ..., -0.88073707,
        -3.6301389 ,  1.9427117 ]], dtype=float32)

In [23]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler
nv = MultinomialNB()
sc = MinMaxScaler()
sc_train = sc.fit_transform(x_train_2d)
sc_test  = sc.fit_transform(x_test_2d)

In [24]:
nv.fit(sc_train,y_train)

MultinomialNB()

In [25]:
sc_train

array([[0.37476763, 0.5603857 , 0.3889339 , ..., 0.3024121 , 0.55368066,
        0.56763107],
       [0.36730635, 0.62208503, 0.33695927, ..., 0.31466255, 0.562757  ,
        0.7185385 ],
       [0.19980219, 0.41260552, 0.31665015, ..., 0.12625006, 0.6111021 ,
        0.60732204],
       ...,
       [0.26311645, 0.57216555, 0.34749562, ..., 0.24063426, 0.5926068 ,
        0.6095055 ],
       [0.57981235, 0.8330513 , 0.31408274, ..., 0.5238551 , 0.33327258,
        0.8362664 ],
       [0.2973741 , 0.60281205, 0.28107408, ..., 0.26947987, 0.51068336,
        0.7451764 ]], dtype=float32)

In [26]:
y_pred = nv.predict(sc_test)
y_pred

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,

In [27]:
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [28]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.71      0.74      0.72       333
           1       0.47      0.43      0.45       180

    accuracy                           0.63       513
   macro avg       0.59      0.59      0.59       513
weighted avg       0.62      0.63      0.63       513

